# Generated by Django 4.2 on 2023-04-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_is_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_tutor',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='wechat_id',
            field=models.CharField(help_text='Your Wechat/Weixin ID used to contact Look4Tutor service', max_length=20, unique=True, verbose_name='wechat ID'),
        ),
    ]
