# Generated by Django 4.2 on 2023-04-15 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('APBI', 'APBI'), ('APSC', 'APSC'), ('BIOL', 'BIOL'), ('CHEM', 'CHEM'), ('COMM', 'COMM'), ('COMR', 'COMR'), ('CPEN', 'CPEN'), ('CPSC', 'CPSC'), ('DCSI', 'DCSI'), ('ECON', 'ECON'), ('ELEC', 'ELEC'), ('EOSC', 'EOSC'), ('MATH', 'MATH'), ('MFRE', 'MFRE'), ('PHIL', 'PHIL'), ('PHYS', 'PHYS'), ('PSYC', 'PSYC'), ('SCIE', 'SCIE'), ('STAT', 'STAT'), ('VANT', 'VANT'), ('WRDS', 'WRDS')], help_text='subject code, e.g. ECON.', max_length=4, unique=True)),
                ('course_number', models.CharField(help_text='3-digits course number, e.g. 101.', max_length=3, unique=True)),
                ('start_date', models.DateField(help_text='Starting date of the term.')),
                ('end_date', models.DateField(help_text='End date of the term.')),
                ('term', models.CharField(choices=[('SPRING', 'SPRING'), ('SUMMER', 'SUMMER'), ('FALL', 'FALL')], help_text='Season of the term.', max_length=6, unique=True)),
                ('section', models.CharField(default='ALL', help_text='Section number, e.g. 202, ALL', max_length=3, unique=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
