# Generated by Django 4.2 on 2023-04-16 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_alter_course_course_number_alter_course_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(help_text='3-digits course number, e.g. 101.', max_length=3, verbose_name='Course Number'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(help_text='End date of the term.', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'is_tutor': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(blank=True, help_text='Section number, e.g. 202 or professor name. <strong>Leave it blank</strong> if there is only one section.', max_length=20, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(help_text='Starting date of the term.', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('APBI', 'APBI'), ('APSC', 'APSC'), ('BIOL', 'BIOL'), ('CHEM', 'CHEM'), ('COMM', 'COMM'), ('COMR', 'COMR'), ('CPEN', 'CPEN'), ('CPSC', 'CPSC'), ('DCSI', 'DCSI'), ('ECON', 'ECON'), ('ELEC', 'ELEC'), ('EOSC', 'EOSC'), ('MATH', 'MATH'), ('MFRE', 'MFRE'), ('PHIL', 'PHIL'), ('PHYS', 'PHYS'), ('PSYC', 'PSYC'), ('SCIE', 'SCIE'), ('STAT', 'STAT'), ('VANT', 'VANT'), ('WRDS', 'WRDS')], help_text='Subject code, e.g. ECON.', max_length=4, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], help_text='Season of the term, e.g. Fall.', max_length=6, verbose_name='Term'),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField(help_text='Enter the week number.', verbose_name='Week No.')),
                ('syllabus', models.TextField(blank=True, help_text='A short syllabus of this lecture.')),
                ('is_midterm', models.BooleanField(default=False, help_text='Is this a midterm review lecture?')),
                ('is_final', models.BooleanField(default=False, help_text='Is this a final review lecture?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('slug', models.SlugField(default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Course')),
            ],
        ),
    ]
