# Generated by Django 4.2 on 2023-04-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_term_remove_course_end_date_remove_course_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='season',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER_1', 'Summer_1'), ('SUMMER_2', 'Summer_2'), ('FALL', 'Fall')], help_text='Season of the term, e.g. Fall.', max_length=8, verbose_name='Season'),
        ),
    ]
