# Generated by Django 4.2 on 2023-04-24 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_term_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.term', verbose_name='Term'),
        ),
    ]
