# Generated by Django 4.2 on 2023-05-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_uploadvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='title',
            field=models.CharField(default='', help_text='Enter the title of the lecture, e.g. Math101 Lecture 1.', max_length=300, verbose_name='Title'),
        ),
    ]
